### ISSUE TITLE
Hemanshu Parmar : Employee.dart

### ISSUE THREAD

**Issue by jaimin1531** [vivekmavani/MobileTraining#1]
https://github.com/vivekmavani/MobileTraining/blob/efcdd6893c104a7154c66b6744cf57004226c997/September/Hemanshu%20Parmar/Dart/Employee.dart#L18

is there any other way that i can achieve a bonus functionality without passing in salary list?

**Comment by ParmarHemanshu** [comment]
Yes we can make parameterized constructor taking the list and use it in giveBonusToEmplyoees() function directly since it is member function of Employee class. I will made this change in my upcoming commit.

**Comment by ParmarHemanshu** [comment]
It is resolved now you can check it.
