### ISSUE TITLE
Hemanshu Parmar : Queue

### ISSUE THREAD

**Issue by jaimin1531** [vivekmavani/MobileTraining#2]
https://github.com/vivekmavani/MobileTraining/blob/efcdd6893c104a7154c66b6744cf57004226c997/September/Hemanshu%20Parmar/Dart/Queue.dart#L4

1. as queue is an heterogeneous data structure i want to store different type of data to queue but right now the implementation is adding only string data. can you update it in such way that we should be able to add any kind of data to it.

https://github.com/vivekmavani/MobileTraining/blob/efcdd6893c104a7154c66b6744cf57004226c997/September/Hemanshu%20Parmar/Dart/Queue.dart#L37
2. wrong print statement.

**Comment by ParmarHemanshu** [comment]
Issue is solved in my next commit .

**Comment by ParmarHemanshu** [comment]
Now stack and queue will perform insert /delete on int,double,string,object and bool kind of hetrogenous data. 
It is fixed now.
