### ISSUE TITLE
Romish Patoriya : Queue

### ISSUE THREAD

**Issue by jaimin1531** [vivekmavani/MobileTraining#6]
https://github.com/vivekmavani/MobileTraining/blob/498fadd0919230c9fff1ae4149a57393634e5cc4/September/Romish%20Patoriya/Dart/Queue.dart#L3

1. as queue is an hetrogeneous data structure make an implementation in such a way that we can add any kind of data to queue.

**Comment by romishpatoriya** [comment]
change the code.
